"""add subscription_type to user

Revision ID: 1a783a77a1d5
Revises: 76dc51eac6c7
Create Date: 2025-05-04 15:22:58.951376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a783a77a1d5'
down_revision = '76dc51eac6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_type')
    # ### end Alembic commands ### 