"""add user analytics table

Revision ID: 47e978273fbd
Revises: adfd2cb42e36
Create Date: 2025-05-04 18:11:35.751780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47e978273fbd'
down_revision = 'adfd2cb42e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_analytics', sa.Column('active_time_minutes', sa.Integer(), nullable=True))
    op.add_column('user_analytics', sa.Column('most_active_day', sa.String(), nullable=True))
    op.add_column('user_analytics', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_analytics', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_user_analytics_date', table_name='user_analytics')
    op.drop_column('user_analytics', 'active_time')
    op.drop_column('user_analytics', 'total_pages')
    op.drop_column('user_analytics', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_analytics', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_analytics', sa.Column('total_pages', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_analytics', sa.Column('active_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_user_analytics_date', 'user_analytics', ['date'], unique=False)
    op.drop_column('user_analytics', 'updated_at')
    op.drop_column('user_analytics', 'created_at')
    op.drop_column('user_analytics', 'most_active_day')
    op.drop_column('user_analytics', 'active_time_minutes')
    # ### end Alembic commands ### 