"""Add analytics tables

Revision ID: a0a61c923e1b
Revises: 47e978273fbd
Create Date: 2025-05-04 18:50:01.628478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0a61c923e1b'
down_revision = '47e978273fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_analytics_id', table_name='user_analytics')
    op.drop_index('ix_user_analytics_user_id', table_name='user_analytics')
    op.drop_table('user_analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_analytics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_chats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_pdfs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active_time_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('most_active_day', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_analytics_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_analytics_pkey')
    )
    op.create_index('ix_user_analytics_user_id', 'user_analytics', ['user_id'], unique=False)
    op.create_index('ix_user_analytics_id', 'user_analytics', ['id'], unique=False)
    # ### end Alembic commands ### 