"""add user analytics table

Revision ID: adfd2cb42e36
Revises: f3042f6967e8
Create Date: 2025-05-04 18:10:16.591273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfd2cb42e36'
down_revision = 'f3042f6967e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total_chats', sa.Integer(), nullable=True),
    sa.Column('total_pdfs', sa.Integer(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('active_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_analytics_date'), 'user_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_user_analytics_id'), 'user_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_user_analytics_user_id'), 'user_analytics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_analytics_user_id'), table_name='user_analytics')
    op.drop_index(op.f('ix_user_analytics_id'), table_name='user_analytics')
    op.drop_index(op.f('ix_user_analytics_date'), table_name='user_analytics')
    op.drop_table('user_analytics')
    # ### end Alembic commands ### 