"""add line_start, line_end, and content to source table

Revision ID: b0678e5c37f5
Revises: a0a61c923e1b
Create Date: 2025-05-06 22:43:33.919049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0678e5c37f5'
down_revision = 'a0a61c923e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('total_chats', sa.Integer(), nullable=True),
    sa.Column('total_pdfs', sa.Integer(), nullable=True),
    sa.Column('active_time_minutes', sa.Float(), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=True),
    sa.Column('messages_received', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_analytics_id'), 'user_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_user_analytics_user_id'), 'user_analytics', ['user_id'], unique=False)
    op.create_table('daily_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analytics_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('minutes_active', sa.Float(), nullable=True),
    sa.Column('chats_created', sa.Integer(), nullable=True),
    sa.Column('pdfs_uploaded', sa.Integer(), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analytics_id'], ['user_analytics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_usage_date'), 'daily_usage', ['date'], unique=False)
    op.create_index(op.f('ix_daily_usage_id'), 'daily_usage', ['id'], unique=False)
    op.add_column('documents', sa.Column('file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_url')
    op.drop_index(op.f('ix_daily_usage_id'), table_name='daily_usage')
    op.drop_index(op.f('ix_daily_usage_date'), table_name='daily_usage')
    op.drop_table('daily_usage')
    op.drop_index(op.f('ix_user_analytics_user_id'), table_name='user_analytics')
    op.drop_index(op.f('ix_user_analytics_id'), table_name='user_analytics')
    op.drop_table('user_analytics')
    # ### end Alembic commands ### 