"""add line_start, line_end, content to sources

Revision ID: ce0dbf800c0c
Revises: b0678e5c37f5
Create Date: 2025-05-06 22:55:06.693300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0dbf800c0c'
down_revision = 'b0678e5c37f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('line_start', sa.Integer(), nullable=True))
    op.add_column('sources', sa.Column('line_end', sa.Integer(), nullable=True))
    op.add_column('sources', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'content')
    op.drop_column('sources', 'line_end')
    op.drop_column('sources', 'line_start')
    # ### end Alembic commands ### 