"""add subscription_type to user

Revision ID: f3042f6967e8
Revises: 1a783a77a1d5
Create Date: 2025-05-04 15:24:21.639626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3042f6967e8'
down_revision = '1a783a77a1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 